services:
  # Servicio PHP-FPM para Laravel
  laravel_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_api
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    expose:
      - 9000

  # Servicio Nginx
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "9080:80"  # Exponer puerto 9080 en el host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - laravel_api
    networks:
      - laravel_network

# Red para permitir que los contenedores se comuniquen entre sí
networks:
  laravel_network:
    driver: bridge
