services:
  # Servicio PHP-FPM para Laravel
  laravel_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_api
    working_dir: /app
    volumes:
      - .:/app
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    expose:
      - 9000

  # Servicio Nginx
  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "9080:80"  # Exponer puerto 9080 en el host
    volumes:
      - .:/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - laravel_api
    networks:
      - laravel_network

# Red para permitir que los contenedores se comuniquen entre sí
networks:
  laravel_network:
    driver: bridge
